### ISSUE TITLE
Non-command-line configuration

### ISSUE THREAD

**Issue by twpayne** [benmanns/goworker#19]
Currently goworker can only be configured with [command-line flags](https://github.com/benmanns/goworker#flags). It would be convenient if goworker could be configured programmatically. This would allow the configuration to be stored elsewhere (e.g. in a application-defined configuration file).

Would you accept a pull request that adds this functionality? Any preference as to how you would like it implemented? I was thinking of something along the lines of:

``` go
package main

// ...

func main() {
    var options = &goworker.Options{
        Queues:      []string{"high", "medium", "low"},
        Connections: 5,
    }
    if err := goworker.Configure(options); err != nil {
        panic(err)
    }
    // ...
}
```

**Comment by sergeylanzman** [comment]
https://github.com/benmanns/goworker/pull/38/files
