### ISSUE TITLE
Allow for maps instead of interfaces for worker functions

### ISSUE THREAD

**Issue by LiterallyElvis** [benmanns/goworker#35]
The getting started page says:

To create a worker, write a function matching the signature
```go
func(string, ...interface{}) error
```

It'd be great if you could instead write functions like
```go
func(string, map[string]string) error
```

for instance, if I wanted to pass a group of files to a worker for processing, I'd have to queue up the job with the right files in the right order in my args parameter, but I'd also have to reference them as args indices. So basically instead of doing something like:

```sh
redis-cli -r 100 RPUSH resque:queue:myqueue '{"class":"MyClass","product_file":"whatever.csv","category_file":"something_else.csv"}'
```
and
```go
func(queue string, args map[string]string) error{
    productFile := os.Open(args["product_file"])
    // more things done here
    return nil
}
```

my actual workflow looks more like
```sh
redis-cli -r 100 RPUSH resque:queue:myqueue '{"class":"MyClass","args":["whatever.csv", "something_else.csv"]}'
```
and
```go
func(queue string,  ...interface{}) error{
    productFileIndex = 0
    productFile := os.Open(args[productFileIndex])
    // more things done here
    return nil
}
```

obviously this isn't the worst problem to have ever, but I think it's a less error prone use case.

**Comment by Aorioli** [comment]
You could always queue the jobs up like this:

`redis-cli -r 100 RPUSH resque:queue:myqueue '{"class":"MyClass","args":["files":{"product_file":"whatever.csv","category_file":"something_else.csv"}]}'`

Your code would look like this:
 
```go
func(queue string, args ...interface{}) error{
    files, ok := args[0].(map[string]string)
    if !ok {
      // error
    }
    productFile := os.Open(files["product_file"])
    // more things done here
    return nil
}
```
The thing is with the interface{} array all kinds of arguments can be queued up, the same way they are in Resque.

**Comment by benmanns** [comment]
@Aorioli has it. We maintain compatibility with Resque (1.x), which uses the array-for-args format. You also have to be careful expecting a `map[string]string` because that can run into issues with formats like nested objects `{"a":{"b":"c"}}`, numeric types `{"a":123}`, and null `{"a":null}`.

You can define a separate handler to help with the repetitive args checking:

```go
func newMapFunc(f func(queue string, args map[string]interface{}) error) (func(queue string, args ...interface{}) error) {
    return func(queue string, args ...interface{}) error {
        if len(args) != 1 {
            // return some error
        }
        mapArgs, ok := args[0].(map[string]interface{})
        if !ok {
            // return some error
        }
        return f(mapArgs)
    }
}

// ...

func someWorker(queue string, args map[string]interface) error{
    path, ok := args["product_file"].(string)
    if !ok {
        // return some error
    }
    productFile := os.Open(path)
    // more things done here
    return nil
}

// ...

goworker.Register("MyClass", newMapFunc(someWorker))
goworker.Register("MyOtherClass", newMapFunc(someOtherWorker))
```

**Comment by LiterallyElvis** [comment]
Oh awesome! Thanks @Aorioli & @benmanns.
