### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by ramonmacias** [benmanns/goworker#61]
Hello we are using go dep for manage all the dependencies of our project and it seems that this tool download the latest tag of goworker project that is "v0.1.2", the thing is that this version doesn't include the WorkerSettings.

Which is the plan to release the next tag?

Thanks

**Comment by benmanns** [comment]
Hey @ramonmacias - I'll do it now.

**Comment by benmanns** [comment]
Pushed tag [v0.1.3](https://github.com/benmanns/goworker/tree/v0.1.3).

**Comment by ramonmacias** [comment]
Many thanks @benmanns !
