### ISSUE TITLE
Any plan to replace garyburd/redigo with gomodule/redigo?

### ISSUE THREAD

**Issue by ZhaoLion** [benmanns/goworker#66]
The repository at [garyburd/redigo](https://github.com/garyburd/redigo/) is a read-only snapshot, i have some project deps on [gomodule/redigo](https://github.com/gomodule/redigo).

I'd happy to hear that you have plan to replace garyburd/redigo with gomodule/redigo. Thanks ! :)

**Comment by benmanns** [comment]
Thanks @ZhaoLion - I'm addressing in #67. As far as I can tell just the path needs updating. Does that look right to you?

**Comment by ZhaoLion** [comment]
Thanks .
